### ISSUE TITLE
TODO 18/04

### ISSUE THREAD

**Issue by IlyaHalsky** [21011996/metastone#1]
- [x] повторить эксперимент на джаве, 2-3 раза переобучив, или запустить несколько раз играть с рандом ботом
- [x] повторить на джаве без активации на последнем слое
- [x] повторить на джаве с 1000 1000 500 слоями
- [x] сделать на питоне с 1000 1000 500 слоями, попробовать " elu" и другие модные функции ативации, использовать l1 l2 нормализацию, попробовать заменить rmsprop на adam, nadam поизменять lr
- [ ] Ранжированные награды (ladder rewards)
- [ ] Повторить 2,3,4,5 пункты на подзадаче с 8 действиями

**Comment by IlyaHalsky** [comment]
(s,s,s,s)
Жаба после 150 с перемешиванием - 73
Жаба после 300 с перемешиванием - 83,64
Жаба после 1000 с перемешиванием - 83,83
NB - 100% невозможно теоретически.

**Comment by IlyaHalsky** [comment]
(s,s,s,l)
Без активации жаба 150 - 83 - возможно забыл потереть нейронку
жаба 300 - 83,67

**Comment by IlyaHalsky** [comment]
(rl,rl,rl,l)
жаба 150 - 74
жаба 300 - 83,66

**Comment by IlyaHalsky** [comment]
(rl, rl, rl, rl, l)
(86, 1000, 1000, 500, 56)
жаба 150 - 
19:52 - 0/150
20:00 - 0/150
недождался

**Comment by IlyaHalsky** [comment]
(rl, rl, rl, rl, l)
(86, 1000, 1000, 500, 56)
питон 150 - разнос

**Comment by IlyaHalsky** [comment]
(elu, elu, elu, lin)
(86, 1000, 1000, 500, 56)
adam, mse
разнос

**Comment by IlyaHalsky** [comment]
Здрасте приехали, Relu в теано криво работает
[NaNs when training ReLU's](https://github.com/fchollet/keras/issues/828)

**Comment by IlyaHalsky** [comment]
Завтра утром попробую с l1 l2, вроде как работает
